services:
  mysql:
    image: mysql:8.0
    container_name: vetsoftware_mysql
    environment:
      MYSQL_ROOT_PASSWORD: cronos2026*
      MYSQL_DATABASE: vetsoftware_db
      MYSQL_USER: cronos
      MYSQL_PASSWORD: "cronos2026*"
    ports:
      - "3306:3306"
    volumes:
      - vetsoftware_mysql_data:/var/lib/mysql

volumes:
  vetsoftware_mysql_data:
